In [2]:
import geopandas as gpd
import pandas as pd

from google.colab import drive

In [14]:
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [17]:
rebanho = pd.read_csv('/content/drive/MyDrive/HomeLab/csv/cns2017_rebanho_tab6908.csv', sep=';', encoding='iso-8859-1')

rebanho.head()

,cod_mun,mun,reb_total,bovino_total,caprino_total,ovino_total,suino_total,aves_total,naofam_total,naofam_bovinos,naofam_caprinos,naofam_ovinos,naofam_suinos,naofam_aves,fam_total,fam_bovinos,fam_caprinos,fam_ovinos,fam_suinos,fam_aves
0,2900108,Abaíra (BA),797,616,36,36,224,528,83,56,4,2,23,51,714,560,32,34,201,477
1,2900207,Abaré (BA),1513,554,1103,1016,359,836,144,41,109,95,42,90,1369,513,994,921,317,746
2,2900306,Acajutiba (BA),326,209,3,14,18,54,42,29,1,9,5,9,284,180,2,5,13,45
3,2900355,Adustina (BA),1481,506,87,654,155,809,259,95,20,106,24,145,1222,411,67,548,131,664
4,2900405,Água Fria (BA),1637,479,44,239,250,1293,336,112,9,59,55,222,1301,367,35,180,195,1071

In [18]:
rebanho.dtypes

cod_mun             int64
mun                object
reb_total           int64
bovino_total        int64
caprino_total      object
ovino_total        object
suino_total        object
aves_total          int64
naofam_total        int64
naofam_bovinos      int64
naofam_caprinos    object
naofam_ovinos      object
naofam_suinos      object
naofam_aves        object
fam_total           int64
fam_bovinos         int64
fam_caprinos       object
fam_ovinos         object
fam_suinos         object
fam_aves            int64
dtype: object

In [19]:
rebanho['fam_caprinos'] = rebanho['fam_caprinos'].replace('-', 0)
rebanho['fam_ovinos'] = rebanho['fam_ovinos'].replace('-', 0)
rebanho['fam_suinos'] = rebanho['fam_suinos'].replace('-', 0)
rebanho['fam_aves'] = rebanho['fam_aves'].replace('-', 0)

rebanho.head()

,cod_mun,mun,reb_total,bovino_total,caprino_total,ovino_total,suino_total,aves_total,naofam_total,naofam_bovinos,naofam_caprinos,naofam_ovinos,naofam_suinos,naofam_aves,fam_total,fam_bovinos,fam_caprinos,fam_ovinos,fam_suinos,fam_aves
0,2900108,Abaíra (BA),797,616,36,36,224,528,83,56,4,2,23,51,714,560,32,34,201,477
1,2900207,Abaré (BA),1513,554,1103,1016,359,836,144,41,109,95,42,90,1369,513,994,921,317,746
2,2900306,Acajutiba (BA),326,209,3,14,18,54,42,29,1,9,5,9,284,180,2,5,13,45
3,2900355,Adustina (BA),1481,506,87,654,155,809,259,95,20,106,24,145,1222,411,67,548,131,664
4,2900405,Água Fria (BA),1637,479,44,239,250,1293,336,112,9,59,55,222,1301,367,35,180,195,1071

In [20]:
rebanho['fam_caprinos'] = rebanho['fam_caprinos'].astype('int')
rebanho['fam_ovinos'] = rebanho['fam_ovinos'].astype('int')
rebanho['fam_suinos'] = rebanho['fam_suinos'].astype('int')
rebanho['fam_aves'] = rebanho['fam_aves'].astype('int')

rebanho.dtypes

cod_mun             int64
mun                object
reb_total           int64
bovino_total        int64
caprino_total      object
ovino_total        object
suino_total        object
aves_total          int64
naofam_total        int64
naofam_bovinos      int64
naofam_caprinos    object
naofam_ovinos      object
naofam_suinos      object
naofam_aves        object
fam_total           int64
fam_bovinos         int64
fam_caprinos        int64
fam_ovinos          int64
fam_suinos          int64
fam_aves            int64
dtype: object

In [21]:
rebanho['naofam_caprinos'] = rebanho['naofam_caprinos'].replace('-', 0)
rebanho['naofam_ovinos'] = rebanho['naofam_ovinos'].replace('-', 0)
rebanho['naofam_suinos'] = rebanho['naofam_suinos'].replace('-', 0)
rebanho['naofam_aves'] = rebanho['naofam_aves'].replace('-', 0)

In [22]:
rebanho['naofam_caprinos'] = rebanho['naofam_caprinos'].astype('int')
rebanho['naofam_ovinos'] = rebanho['naofam_ovinos'].astype('int')
rebanho['naofam_suinos'] = rebanho['naofam_suinos'].astype('int')
rebanho['naofam_aves'] = rebanho['naofam_aves'].astype('int')

In [23]:
rebanho.dtypes

cod_mun             int64
mun                object
reb_total           int64
bovino_total        int64
caprino_total      object
ovino_total        object
suino_total        object
aves_total          int64
naofam_total        int64
naofam_bovinos      int64
naofam_caprinos     int64
naofam_ovinos       int64
naofam_suinos       int64
naofam_aves         int64
fam_total           int64
fam_bovinos         int64
fam_caprinos        int64
fam_ovinos          int64
fam_suinos          int64
fam_aves            int64
dtype: object

In [24]:
rebanho['caprino_total'] = rebanho['caprino_total'].replace('-', 0)
rebanho['ovino_total'] = rebanho['ovino_total'].replace('-', 0)
rebanho['suino_total'] = rebanho['suino_total'].replace('-', 0)

In [25]:
rebanho['caprino_total'] = rebanho['caprino_total'].astype('int')
rebanho['ovino_total'] = rebanho['ovino_total'].astype('int')
rebanho['suino_total'] = rebanho['suino_total'].astype('int')

rebanho.dtypes

cod_mun             int64
mun                object
reb_total           int64
bovino_total        int64
caprino_total       int64
ovino_total         int64
suino_total         int64
aves_total          int64
naofam_total        int64
naofam_bovinos      int64
naofam_caprinos     int64
naofam_ovinos       int64
naofam_suinos       int64
naofam_aves         int64
fam_total           int64
fam_bovinos         int64
fam_caprinos        int64
fam_ovinos          int64
fam_suinos          int64
fam_aves            int64
dtype: object

In [26]:
rebanho2017 = rebanho.to_csv('/content/drive/MyDrive/HomeLab/csv/rebanho2017.csv')